name = "teacher-review-system"
compatibility_date = "2024-05-15"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[env.production]
vars = { NODE_ENV = "production" }

[env.production.vars]
# 生产环境变量将在Cloudflare Pages dashboard中设置 