# Cloudflare Pages的配置文件
name = "no-name-review"
compatibility_date = "2023-09-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"

[site]
bucket = ".vercel/output/static"

[build.upload]
format = "service-worker" 